/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 *****************************************************************************
 * Project  : STM32 Register-Level ADC Driver Development
 * Exercise : Multi-Channel ADC using Scan Mode and Polling
 *
 * Description:
 * ------------
 * This exercise validates the operation of a configuration-driven ADC driver
 * for acquiring multiple analog inputs using a single ADC peripheral. The ADC
 * is configured in Scan Mode, allowing multiple channels to be converted
 * sequentially after a single software trigger.
 *
 * Two analog input channels are configured as a regular conversion sequence.
 * Each channel has its own sampling time and conversion rank. The sequence
 * length is automatically programmed based on the number of configured
 * channels, enabling the driver to support scalable multi-channel
 * configurations without modifying the driver source code.
 *
 * Since the application uses polling to retrieve conversion results, the ADC
 * is configured to generate an End Of Conversion (EOC) event after every
 * individual channel conversion (EOCS = 1). This allows the software to wait
 * for each conversion, read the Data Register, and store the corresponding
 * digital value before the next channel conversion completes.
 *
 * Objective:
 * ----------
 * Validate the register-level implementation of Scan Mode by configuring
 * multiple ADC channels and verifying that each configured channel is
 * converted in the programmed sequence.
 *
 * Hardware Configuration:
 * -----------------------
 * MCU               : STM32F407 Discovery
 * ADC Module        : ADC1
 * Analog Inputs     : PA1 (ADC Channel 1)
 *                     PA3 (ADC Channel 3)
 * Analog Sources    : Two Potentiometers
 * Resolution        : 12-bit
 * Trigger           : Software Trigger (SWSTART)
 * Scan Mode         : Enabled
 * Continuous Mode   : Disabled
 * EOC Selection     : End Of Conversion after each channel
 * Alignment         : Right Alignment
 * Sample Time       : 480 Cycles (Both Channels)
 *
 * Configuration Summary:
 * ----------------------
 * GPIO Configuration
 *      PA1 -> Analog Mode
 *      PA3 -> Analog Mode
 *
 * ADC Conversion Sequence
 *      Rank 1 -> Channel 1
 *      Rank 2 -> Channel 3
 *
 * Sequence Length
 *      2 Regular Conversions
 *
 * Runtime Flow:
 * -------------
 * while(1)
 * {
 *      adc_start_conversion(adc1_ptr);
 *
 *      adc_get_value(adc1_ptr, &adc_measurement[0]);
 *      adc_get_value(adc1_ptr, &adc_measurement[1]);
 * }
 *
 * Conversion Sequence:
 * --------------------
 *
 *             SWSTART
 *                |
 *                V
 *        Channel 1 (Rank 1)
 *                |
 *               EOC
 *                |
 *          Read Data Register
 *                |
 *                V
 *        Channel 3 (Rank 2)
 *                |
 *               EOC
 *                |
 *          Read Data Register
 *                |
 *               EOS
 *                |
 *                V
 *        Sequence Complete
 *
 * Expected Result:
 * ----------------
 * Rotating either potentiometer changes only the corresponding ADC result,
 * demonstrating that both analog channels are independently converted and
 * stored in the correct order.
 *
 * Learning Outcomes:
 * ------------------
 * ✓ Configured multiple GPIO pins for analog operation.
 * ✓ Implemented multi-channel ADC configuration.
 * ✓ Programmed Regular Conversion Sequence (SQR Registers).
 * ✓ Configured Scan Mode for sequential channel conversion.
 * ✓ Configured sequence length automatically.
 * ✓ Configured independent sampling times for multiple channels.
 * ✓ Understood the importance of EOC generation during polling.
 * ✓ Validated sequential acquisition of multiple analog channels using a
 *   single ADC peripheral.
 * ✓ Demonstrated a scalable configuration-driven ADC driver architecture.
 *
 * Debugging Notes:
 * ----------------
 * During development, two important issues were identified and resolved:
 *
 * 1. The EOC Selection (EOCS) bit was initially programmed incorrectly,
 *    preventing the ADC from generating an End Of Conversion event after
 *    every individual conversion.
 *
 * 2. The second ADC channel (Channel 3) did not produce valid results because
 *    its corresponding GPIO pin (PA3) had not been configured in Analog Mode.
 *    After configuring PA3 correctly, both channels were converted and read
 *    successfully.
 *
 ******************************************************************************/

#include <stdint.h>
#include <app_main.h>
#include <service.h>
#include <app_feature.h>
#include "APP_task.h"
#include "APP_config.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void service_init()
{
	 FPU_Enable();
	 nvic_init(38);
	 gpio_init(gpio_pin_config , gpio_pin_config_size);
	 uart_init(uart_config , uart_config_size);
}

void app_init()
{
	;
}

int main(void)
{

	service_init();
    app_init();



    while(1)
    {

    	uart_print_interrupt_method("anas abdulla\r\n");
    	uart_print_interrupt_method("Anas\r\n");
//    	adc_start_conversion(adc1_ptr);
//    	adc_start_conversion(adc2_ptr);
//    	adc_get_value(adc1_ptr , &adc_measurement[0]);
//    	adc_get_value(adc1_ptr , &adc_measurement[1]);
//    	adc_get_value(adc2_ptr , &adc_measurement[2]);
    }
}
